name: publish to DFinity Internet Computer
on:
  pull_request:
  push:
    branches: [master]

jobs:
  publish:
    name: build and publish to Dfinity IC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy canisters
        id: deploy
        uses: fleekhq/ic-deploy-action@v2
        with:
          identity: ${{ secrets.DFX_IDENTITY }}
          wallets: ${{ secrets.DFX_WALLETS }}
          dfx_params: --no-wallet
      - name: Show success message
        run: echo success!